version: "3.7"

services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp-collinmbarrett:
    depends_on:
      - db
    image: wordpress:php7.3-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - static-data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - wp-collinmbarrett
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-data:/var/www/html
      - log-data:/var/log
    restart: always

volumes:
  db-data:
  static-data:
  log-data: