version: "3.7"

services:
  mysql:
    image: mariadb:10
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp-collinmbarrett:
    image: wordpress:php7.3-fpm-alpine
    depends_on:
      - mysql
    volumes:
      - wp-collinmbarrett:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    links:
      - wp-collinmbarrett
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/svr-includes:/etc/nginx/svr-includes
      - ~/cert:/etc/nginx/cert
      - wp-collinmbarrett:/var/www/html/wp-collinmbarrett

volumes:
  mysql-data:
  wp-collinmbarrett:
