version: "3.7"

services:
  db:
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp-collinmbarrett:
    depends_on:
      - db
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - static-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    links:
      - wp-collinmbarrett
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-data:/var/www/html
      - nginx-logs:/var/log

volumes:
  db-data:
  static-data:
  nginx-logs:
