version: "3.7"

services:
  wp-db:
    image: mariadb:10
    volumes:
      - wp-db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp-collinmbarrett:
    depends_on:
      - wp-db
    image: wordpress:php7.3-fpm-alpine
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  wp-db_data: {}
