version: "3.7"

services:
  wp_jennythebaker-com:
    image: wordpress:php7.3-fpm-alpine
    restart: always
    networks:
      - reverse-proxy
      - jennythebaker-com
    depends_on:
      - mariadb_jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb_jennythebaker-com:3306
      WORDPRESS_DB_NAME: ${WP_JENNYTHEBAKER_WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WP_JENNYTHEBAKER_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_JENNYTHEBAKER_WORDPRESS_DB_PASSWORD}

  redis_jennythebaker-com:
    image: redis:32bit-stretch
    restart: always
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_cache:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb_jennythebaker-com:
    image: mariadb:10
    restart: always
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_JENNYTHEBAKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_JENNYTHEBAKER_WORDPRESS_DB_NAME}
      MYSQL_USER: ${WP_JENNYTHEBAKER_WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WP_JENNYTHEBAKER_WORDPRESS_DB_PASSWORD}

  wp-cli_jennythebaker-com:
    image: wordpress:cli-php7.3
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html

networks:
  jennythebaker-com:

volumes:
  jennythebaker-com_files:
  jennythebaker-com_cache:
  jennythebaker-com_data:
